### PR TITLE
Support optional environment hash

### LINKED ISSUE #6: Support for setting environment variables
IO.popen can take "an optional first argument" (yup!) specifying environment variables for the command to run. That would be super handy in this gem as well - maybe something a little nicer than an optional first argument, though...

### PR DESCRIPTION
**Pull request by olefriis**
Fixes #6

### CODE REVIEW

**Comment by olefriis** [comment]
Ah, darn! `IO#popen` doesn't support an `env` parameter in Ruby 1.9. Is there any reason the gem needs Ruby 1.9 support, or could we just drop that at the same time?

I'll update the pull request with the removal of Ruby 1.9 testing... It's up to @kamstrup whether this is OK or not :-)

**Comment by kamstrup** [comment]
The 1.9 support was added on request from @jmoody because they need it in calabash. The Ruby docs are very ambiguous about env support in IO.popen... :-/ http://ruby-doc.org/core-1.9.3/IO.html#method-c-popen. Can't figure out if there is some way to support on this on ancient Rubies

**Comment by jmoody** [comment]
@olefriis @kamstrup Let's drop ruby 1.9.  I have announced to the Calabash community that we are going to drop ruby 1.9 shortly.  I have already worked around the 1.9 issue in run-loop by branching on the version (while I was waiting for my fix to be released).

Apologies for stomping all over your gem @kamstrup

**Comment by kamstrup** [comment]
Ok. I'll merge this, and revert to using keyword args in stead of *opt blobs. Next release will have minor version bumped to indicate backwards compat broken (for older rubies only)

**Pull request merged**
